<?xml version="1.0" encoding="utf-8"?>
<definitions name ="poService"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             targetNamespace="http://localhost/WebServices/wsdl/po.wsdl">
    <message name="getPlaceOrderInput">
        <part name="body" element="xsd:string"/>
    </message>
    <message name="getPlaceOrderOutput">
        <part name="body" element="xsd:string"/>
    </message>
    <portType name="poServicePortType">
        <operation name="placeOrder">
           <input message="tns:getPlaceOrderInput"/>
           <output message="tns:getPlaceOrderOutput"/>
        </operation>
    </portType>
    <binding name="poServiceBinding" type="tns:poServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="placeOrder">
           <soap:operation soapAction="http://localhost/WebServices/ch2/placeOrder"/>
           <input>
               <soap:body use="literal"/>
           </input>
           <output>
               <soap:body use="literal"/>
           </output>
        </operation>
    </binding>
    <service name="poService">
        <port name="poServicePort" binding="tns:poServiceBinding">
           <soap:address location="http://localhost/WebServices/ch2/SOAPServer_ext.php"/>
        </port>
    </service>
</definitions>
