<?xml version="1.0" encoding="utf-8"?>
<definitions name ="thread1Service"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             targetNamespace="http://localhost/WebServices/wsdl/thread1"
             xmlns:tns="http://localhost/WebServices/wsdl/thread1">
    <message name="thread1Input">
        <part name="payload" type="xsd:string"/>
    </message>
    <portType name="thread1PortType">
        <operation name="startThread1">
           <input message="tns:thread1Input"/>
        </operation>
    </portType>
    <binding name="thread1ServiceBinding" type="tns:thread1PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="startThread1">
           <soap:operation soapAction="http://localhost/WebServices/ch7/startThread1"/>
           <input>
               <soap:body use="literal"/>
           </input>
        </operation>
    </binding>
    <service name="thread1Service">
        <port name="thread1ServicePort" binding="tns:thread1ServiceBinding">
           <soap:address location="http://localhost/WebServices/ch7/SOAPServer_thread1.php"/>
        </port>
    </service>
</definitions>
